In [79]:
import torch
import gym
from gym import envs
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np

In [3]:
for env in envs.registry.all():
    print(env)

EnvSpec(AtlantisNoFrameskip-v4)
EnvSpec(BankHeist-ram-v4)
EnvSpec(Berzerk-ramDeterministic-v0)
EnvSpec(Gravitar-ram-v4)
EnvSpec(IceHockey-ram-v4)
EnvSpec(ReversedAddition3-v0)
EnvSpec(Asteroids-ramDeterministic-v0)
EnvSpec(PitfallDeterministic-v0)
EnvSpec(PooyanDeterministic-v0)
EnvSpec(NameThisGameNoFrameskip-v0)
EnvSpec(HandManipulateBlockRotateParallelTouchSensors-v0)
EnvSpec(DoubleDunk-ram-v0)
EnvSpec(Qbert-ramDeterministic-v0)
EnvSpec(Centipede-ram-v4)
EnvSpec(BankHeist-ramDeterministic-v4)
EnvSpec(VentureDeterministic-v0)
EnvSpec(IceHockey-ramDeterministic-v0)
EnvSpec(TimePilotNoFrameskip-v0)
EnvSpec(ChopperCommandDeterministic-v0)
EnvSpec(JamesbondNoFrameskip-v0)
EnvSpec(Atlantis-ramNoFrameskip-v0)
EnvSpec(ElevatorAction-v0)
EnvSpec(Robotank-ram-v0)
EnvSpec(Asterix-ramNoFrameskip-v0)
EnvSpec(FetchPushDense-v1)
EnvSpec(Boxing-ramNoFrameskip-v4)
EnvSpec(BipedalWalker-v2)
EnvSpec(Asteroids-v0)
EnvSpec(HandManipulateEggDense-v0)
EnvSpec(WizardOfWor-v0)
EnvSpec(Krull-ramDeterministic

In [1]:
env = gym.make('PongNoFrameskip-v0')
observation = env.reset()


env.render()
print(observation)
action = env.action_space.sample()
a, b, c, d = env.step(action)
print(a,b,c,d)

env.close()


[[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [109 118  43]
  [109 118  43]
  [109 118  43]]

 [[109 118  43]
  [109 118  43]
  [109 118  43]
  ...
  [109 118  43]
  [109 118  43]
  [109 118  43]]

 [[109 118  43]
  [109 118  43]
  [109 118  43]
  ...
  [109 118  43]
  [109 118  43]
  [109 118  43]]

 ...

 [[ 53  95  24]
  [ 53  95  24]
  [ 53  95  24]
  ...
  [ 53  95  24]
  [ 53  95  24]
  [ 53  95  24]]

 [[ 53  95  24]
  [ 53  95  24]
  [ 53  95  24]
  ...
  [ 53  95  24]
  [ 53  95  24]
  [ 53  95  24]]

 [[ 53  95  24]
  [ 53  95  24]
  [ 53  95  24]
  ...
  [ 53  95  24]
  [ 53  95  24]
  [ 53  95  24]]]
[[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [109 118  43]
  [109 118  43]
  [109 118  43]]

 [[109 118  43]
  [109 118  43]
  [109 118  43]
  ...
  [109 118  43]
  [109 118  43]
  [109 118  43]]

 [[109 118  43]
  [109 118  43]
  [109 118  43]
  ...
  [109 118  43]
  [109 118  43]
  [109 118  43]]

 ...

 [[ 53  95  24]
  [ 53  95  24]
  [ 53  95  24]
  ..

In [ ]:
#Run to see visual
"""
for i_episode in range(1000):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        a, b, c, d, e, f = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break
env.close()
"""

In [2]:
env = gym.make('PongNoFrameskip-v0')
observation = env.reset()


# env.render()
print(observation)
# action = env.action_space.sample()
# a, b, c, d = env.step(action)
# print(a,b,c,d)

env.close()


[[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [109 118  43]
  [109 118  43]
  [109 118  43]]

 [[109 118  43]
  [109 118  43]
  [109 118  43]
  ...
  [109 118  43]
  [109 118  43]
  [109 118  43]]

 [[109 118  43]
  [109 118  43]
  [109 118  43]
  ...
  [109 118  43]
  [109 118  43]
  [109 118  43]]

 ...

 [[ 53  95  24]
  [ 53  95  24]
  [ 53  95  24]
  ...
  [ 53  95  24]
  [ 53  95  24]
  [ 53  95  24]]

 [[ 53  95  24]
  [ 53  95  24]
  [ 53  95  24]
  ...
  [ 53  95  24]
  [ 53  95  24]
  [ 53  95  24]]

 [[ 53  95  24]
  [ 53  95  24]
  [ 53  95  24]
  ...
  [ 53  95  24]
  [ 53  95  24]
  [ 53  95  24]]]


In [3]:
type(observation)

numpy.ndarray

In [6]:
pobservation = torch.from_numpy(observation)
pobservation

tensor([[[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [109, 118,  43],
         [109, 118,  43],
         [109, 118,  43]],

        [[109, 118,  43],
         [109, 118,  43],
         [109, 118,  43],
         ...,
         [109, 118,  43],
         [109, 118,  43],
         [109, 118,  43]],

        [[109, 118,  43],
         [109, 118,  43],
         [109, 118,  43],
         ...,
         [109, 118,  43],
         [109, 118,  43],
         [109, 118,  43]],

        ...,

        [[ 53,  95,  24],
         [ 53,  95,  24],
         [ 53,  95,  24],
         ...,
         [ 53,  95,  24],
         [ 53,  95,  24],
         [ 53,  95,  24]],

        [[ 53,  95,  24],
         [ 53,  95,  24],
         [ 53,  95,  24],
         ...,
         [ 53,  95,  24],
         [ 53,  95,  24],
         [ 53,  95,  24]],

        [[ 53,  95,  24],
         [ 53,  95,  24],
         [ 53,  95,  24],
         ...,
         [ 53,  95,  24],
        

In [20]:
flattened_pobservation = pobservation.view(1,-1).float()

In [21]:
lenobs = len(flattened_pobservation[0])
lenobs

100800

In [22]:
flattened_pobservation.shape

torch.Size([1, 100800])

In [210]:
lenobs = 100800
ANNmodel = nn.Sequential(
           nn.Linear(lenobs, 2000),
           nn.Sigmoid(),
           nn.Linear(2000,2),
           nn.LogSoftmax(dim = 1))

In [100]:
preds = ANNmodel(flattened_pobservation)

In [117]:
action = np.random.choice(np.array([0,1]), p = preds.view(2,).data.numpy())
action

1

In [205]:
############################# Experimenting with Backpropagation ######################

inp = torch.tensor([2.,3.]).float()
weights = torch.tensor([1.,9.], requires_grad = True).float()
print("Params: ",weights)
gt = torch.tensor([6.])
print("Ground truth: ",gt)
out = torch.dot(inp,weights)
print("Prediction: ",out)

error = (gt - out)



Params:  tensor([1., 9.], requires_grad=True)
Ground truth:  tensor([6.])
Prediction:  tensor(29., grad_fn=<DotBackward>)


In [206]:
optimizer = optim.SGD([weights],lr = 0.1)
optimizer.zero_grad()
error.backward()
optimizer.step()

# print(ANNmodel.weight.grad)
weights.grad, out.grad

(tensor([-2., -3.]), None)

In [207]:
#Weights after one round of backpropagation
weights

tensor([1.2000, 9.3000], requires_grad=True)

In [208]:
# Checking variables with requires_grad
inp.requires_grad, weights.requires_grad, gt.requires_grad, out.requires_grad, error.requires_grad

(False, True, False, True, True)

In [209]:
###############################################################################################

In [ ]:
############################ Manually setting gradients #######################################

In [262]:
MinorModel2 = nn.Sequential( 
             nn.Linear(2,1, bias = False))

inp = torch.tensor([2.,3.])
out = MinorModel(inp)
out

tensor([-0.8636], grad_fn=<SqueezeBackward3>)

In [263]:
for params in MinorModel2.parameters():
    print(params)

Parameter containing:
tensor([[0.2423, 0.0213]], requires_grad=True)


In [264]:
MinorModel2[0].weight

Parameter containing:
tensor([[0.2423, 0.0213]], requires_grad=True)

In [265]:
MinorModel2[0].weight.grad = torch.Tensor([1,2]).view(1,-1)

In [267]:
o2 = optim.SGD(MinorModel2.parameters(), lr=0.1)

o2.step()

In [268]:
for params in MinorModel2.parameters():
    print(params)

Parameter containing:
tensor([[ 0.1423, -0.1787]], requires_grad=True)


In [ ]:
########################################################

In [ ]:
####################### Testing ########################

In [57]:

MinorModel = nn.Sequential( 
             nn.Linear(2,1, bias = False))

inp = torch.tensor([2.,3.])
out = MinorModel(inp)
out


tensor([-0.8636], grad_fn=<SqueezeBackward3>)

In [40]:

for name, params in MinorModel.named_parameters():
    print(name, params)
    


0.weight Parameter containing:
tensor([[-0.6444, -0.6648]], requires_grad=True)


In [216]:

for params in MinorModel.parameters():
    print(params)
    print(type(params))
    
print(MinorModel.parameters())


Parameter containing:
tensor([[ 0.0408, -0.3151]], requires_grad=True)
<class 'torch.nn.parameter.Parameter'>
<generator object Module.parameters at 0x7f7a06389620>


In [ ]:
#######################################################